name: run-node-script

on:
  workflow_dispatch: # Trigger manually, or adjust (e.g., schedule or push)

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Debug Env (Safe)
        run: echo "REDIS_KEY is ${REDIS_KEY:0:5}*****"
        env:
          REDIS_KEY: ${{ secrets.REDIS_KEY }}

      - name: Run RSS Parser
        env:
          REDIS_KEY: ${{ secrets.REDIS_KEY }}
        run: node fetch_rss.js
